version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:304683306596:task-definition/hello-world-rest-api-code-pipeline-aws-ecs:1"
        LoadBalancerInfo:
          ContainerName: "aws-hello-world-rest-api"
          ContainerPort: "80"
        PlatformVersion: "LATEST"